import Navbar from "@/components/layout/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Carter_One } from "next/font/google";
import {
  CategoriesContext,
  CategoriesContextProvider,
} from "@/store/CategoriesContext";
import CategoryList from "@/components/CategoryList";

import { CartContextProvider } from "@/store/CartContext";
import Cart from "@/components/Cart";
import OverLay from "@/components/UI/OverLay";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CategoriesContextProvider>
          <CartContextProvider>

            <div className="bg-background text-white min-h-[100vh] " >
              <div className="max-w-5xl mx-auto relative overflow-x-hidden " >
                <Navbar />
                <CategoryList />
                {children}
              </div>
                <OverLay />
                <Cart />

            </div>
          </CartContextProvider>
        </CategoriesContextProvider>
      </body>
    </html>
  );
}
